name: Publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for github-action-get-previous-tag

      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Get next minor version
        id: semver
        uses: 'WyriHaximus/github-action-next-semvers@v1'
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create release
        id: create_release_id
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.patch }}
          release_name: Release ${{ steps.semver.outputs.patch }}

      - name: Build
        run: |
          docker build -t hamolicious/configuration-less-generic-stub:${{ steps.semver.outputs.patch }}  .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hamolicious
          password: ${{ secrets.DOCKER_PASS }}

      - name: Publish image
        run: |
          docker push hamolicious/configuration-less-generic-stub:${{ steps.semver.outputs.patch }}
